Module1:Modal popup
derrick1451/Mobile-Portfolio pull request #13
Opened 2023-04-14 14:38 UTC by derrick1451

- ### Modal popup
- In this module, we implemented the popup window on both the mobile and desktop screens 
- we achieved this by

1. Update the HTML and generated the work-section dynamically
2. Edit the CSS files

2023-04-14 14:46 UTC, AshakaE commented
### Hi Team 🙋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

You have submitted a project, that doesn't have commit history from every team member, as a team project everyone is expected to have an input in the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 07:50 UTC, derrick1451 commented
my coding partner actually left the program so am really supposed to do the work individually

2023-04-19 08:02 UTC, amejid reviewed
Hi @derrick1451, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commits from your coding partner. Please contact student success and provide a screenshot of the permission given by them to work solo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 13:22 UTC, derrick1451 commented
[image: Screenshot from 2023-04-19 16-19-24.png]

On Wed, Apr 19, 2023 at 11:02 AM Abdelmejid Oumer Ali <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hi @derrick1451 <https://github.com/derrick1451>,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that does not have commits from your coding
> partner. Please contact student success and provide a screenshot of the
> permission given by them to work solo.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/derrick1451/Mobile-Portfolio/pull/13#pullrequestreview-1391494922>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APTJN7BEO6OK3E53YEKQORTXB6LZPANCNFSM6AAAAAAW6QKNUQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-19 13:26 UTC, derrick1451 commented
thats the recent email l received from success permitting to work on the
task individually


On Wed, Apr 19, 2023 at 4:22 PM Hayle Derrick ***@***.***>
wrote:

> [image: Screenshot from 2023-04-19 16-19-24.png]
>
> On Wed, Apr 19, 2023 at 11:02 AM Abdelmejid Oumer Ali <
> ***@***.***> wrote:
>
>> ***@***.**** commented on this pull request.
>>
>> Hi @derrick1451 <https://github.com/derrick1451>,
>>
>> While you made a great effort in this project, unfortunately, I cannot
>> proceed to review your code.
>> Invalid Code Review Request
>>
>> You have submitted a project, that does not have commits from your coding
>> partner. Please contact student success and provide a screenshot of the
>> permission given by them to work solo.
>>
>> Your Code Review Request will be marked as invalid in your Dashboard, so
>> please submit a new one once you are ready 🙏
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *Invalid Code Review Request does not count into the code reviews limit.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/derrick1451/Mobile-Portfolio/pull/13#pullrequestreview-1391494922>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/APTJN7BEO6OK3E53YEKQORTXB6LZPANCNFSM6AAAAAAW6QKNUQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-04-19 13:33 UTC, franclobo reviewed
Hi @derrick1451, 

![terminator](https://user-images.githubusercontent.com/58642949/233091160-99378ffe-b6f1-4ad5-9772-d4a0310a625d.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair-programming activity and doesn't have commits from your partner. The image that proves that student success has authorized you to work alone has not charged correctly 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/233091071-fea2169f-ed38-4fa9-8ede-45a638999a40.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 13:47 UTC, derrick1451 commented
these are the screenshots to prove that student success has permitted me

On Wed, Apr 19, 2023 at 4:33 PM Francisco Borja Lobato <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hi @derrick1451 <https://github.com/derrick1451>,
>
> [image: terminator]
> <https://user-images.githubusercontent.com/58642949/233091160-99378ffe-b6f1-4ad5-9772-d4a0310a625d.gif>
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that is a pair-programming activity and
> doesn't have commits from your partner. The image that proves that student
> success has authorized you to work alone has not charged correctly 👇🏽
>
> [image: image]
> <https://user-images.githubusercontent.com/58642949/233091071-fea2169f-ed38-4fa9-8ede-45a638999a40.png>
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/derrick1451/Mobile-Portfolio/pull/13#pullrequestreview-1392084128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APTJN7A7EOPL27I2DQEMUH3XB7STFANCNFSM6AAAAAAW6QKNUQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-19 13:51 UTC, derrick1451 commented
![Screenshot from 2023-04-19 16-44-54](https://user-images.githubusercontent.com/65443580/233096212-385d2897-b394-42f2-a61f-d130e4bbe1b4.png)
![Screenshot from 2023-04-19 16-44-05](https://user-images.githubusercontent.com/65443580/233096327-40190e56-75c4-4701-b8ca-fa2ee654ee25.png)

2023-04-19 14:44 UTC, emmiiorji requested changes
Hi @derrick1451, 
# Status: Changes Required ♻️

Good job so far! Sorry for having to work alone and the hitches experienced.

There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Popup appears on click of "See Project" button
- The popup is able to close using the close button
- Good use of array to hold all projects


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 14:44 UTC, emmiiorji commented on style.css
> +
Kindly adjust the design on mobile version to be as close to the design as possible. Check the illustration below for more detail.

Your design:
![image](https://user-images.githubusercontent.com/20554583/233106202-85df4013-75ec-4fc4-88de-e1d6c51b5676.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/233106356-953831e3-aa8d-4e38-b6fd-e743bade852d.png)

2023-04-19 14:44 UTC, emmiiorji commented on style.css
> +  }
On the desktop version, kindly adjust the design to be as close to the design as possible. Check the illustration below for details:

Your design:
![image](https://user-images.githubusercontent.com/20554583/233111988-6c1b80b1-7e65-4b64-9a45-f91e18b17481.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/233111117-73e6c482-da97-44c1-ab98-6881c76396b3.png)

2023-04-20 12:36 UTC, AdnanOlarmmi approved these changes
Hi @derrick1451,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice one fixing the required changes.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 13:15 UTC, merged