Module 1:store form inputs with local storage
derrick1451/Mobile-Portfolio pull request #15
Opened 2023-04-21 10:24 UTC by derrick1451

### Local storage 

- We updated our page and implemented local storage on it by

1. Using javascript and the dom 
2. Editng the HTML file
3. Make a few changes to the CSS

2023-04-21 10:27 UTC, derrick1451 commented
![Screenshot from 2023-04-19 16-44-05](https://user-images.githubusercontent.com/65443580/233613708-b5c9cc33-3ca1-491f-b9b8-70cc36e2ea75.png)

2023-04-21 10:56 UTC, AlphaNtihinduka requested changes
## Hi @Ibizugbe    🙋‍♂️
Good job working on preserving form data in the local storage. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! 🚶: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

# Required Changes :recycle: 
- Kindly consider the inline review comments.
- Additionally, I have noticed that your Readme has a broken MIT link. Kindly ensure to fix this so that other developers are able to access your license.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-04-21 10:56 UTC, AlphaNtihinduka commented on script.js
> +  });
- [ ] I can see the form information is stored in the local storage when the user inputs the data into the form. Which is a very great achievement 👏. I can say we are very close to completing the form data preserve. If you noticed, you are not having the part that can help you to retrieve data from local storage. Therefore I suggest that you modify your code to make sure that the contact form information is persistent to page reloads ☺️.

2023-04-21 11:14 UTC, derrick1451 commented
Could you please through more light on the issue cos am lost with the
review
Do you mean using the getitem or

On Fri, Apr 21, 2023, 13:56 NTIHINDUKA ALPHA ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @Ibizugbe <https://github.com/Ibizugbe> 🙋‍♂️
>
> Good job working on preserving form data in the local storage. You have
> done the design to the best expectation and incredibly well. 👏
>
> You still need to implement few on the project but you are almost there!!!
> 🚶:
>
> TO HIGHLIGHT:
>
>    - Your project is professional ✅
>    - Professional README file 💯
>    - Your PR is professional ✅
>    - Well-structured files ✅
>
> STATUS: Required Changes ♻️
>
> [image: close]
> <https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif>
> Required Changes ♻️
>
>    - Kindly consider the inline review comments.
>    - Additionally, I have noticed that your Readme has a broken MIT link.
>    Kindly ensure to fix this so that other developers are able to access your
>    license.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread or slack
> channel if something is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> HAPPY CODING AND GOOD LUCK 🤞 🍀
> ------------------------------
>
> In script.js
> <https://github.com/derrick1451/Mobile-Portfolio/pull/15#discussion_r1173631344>
> :
>
> > +const formItems = document.querySelectorAll('.form-container');
> +const formData = Array.from(formItems);
> +formData.forEach((form) => {
> +  form.addEventListener('input', (e) => {
> +    const letter = e.target.id;
> +    data[letter] = e.target.value;
> +    const dataMarker = JSON.stringify(data);
> +    localStorage.setItem('data', dataMarker);
> +  });
>
>
>    - I can see the form information is stored in the local storage when
>    the user inputs the data into the form. Which is a very great achievement
>    👏. I can say we are very close to completing the form data preserve.
>    If you noticed, you are not having the part that can help you to retrieve
>    data from local storage. Therefore I suggest that you modify your code to
>    make sure that the contact form information is persistent to page reloads
>    ☺️.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/derrick1451/Mobile-Portfolio/pull/15#pullrequestreview-1395548453>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APTJN7CARJXHZ3I2FKF6K43XCJRXNANCNFSM6AAAAAAXGV6FT4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-22 11:37 UTC, aamirkhan2478 approved these changes
Hi @derrick1451 , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 12:02 UTC, merged

2023-04-25 14:43 UTC, AlphaNtihinduka commented
Dear @derrick1451 I am sorry that I wasn't able to read your comment as earlier as it could be possible. However, what you thought about was the requirement I was suggesting for. Please incase you have a question, you should remember to tag the reviewer so that he/she can get the notification for quick response. I am happy that your project was approved and congratulations 👍.
HAPPY CODING.